### ISSUE TITLE
The failure of translation changes images

### ISSUE THREAD

**Issue by variety754** [LucasGGamerM/moshidon#381] opened 2024-04-25 11:08 UTC
**Describe the bug**

When tapping on translate button and translation fails, sometimes the image of the post changes to the image of another post near

**To reproduce**
1. Find a post with an image and with disabled translations (or just use the one from the video: https://colloquium.social/@aslanmane/112331489036373100)
2. Tap on translation button
3. See the issue

**Screenshots and screen recordings**

https://github.com/LucasGGamerM/moshidon/assets/124847943/bb29d39c-5f36-424b-ae32-7d3ce0332ba4

**Version**

Moshidon version: 2.1.4+fork.104.moshinda (104)

**Comment by LucasGGamerM** [comment] 2024-04-26 08:57
Yes, sometime ago. I could find the source of the issue, but it seems like the failure might have something to do with it

**Comment by LucasGGamerM** [comment] 2024-04-26 08:59
This is a duplicate of #335, so we will discuss this there and this issue shall be closed

**Closed by LucasGGamerM** 2024-04-26 08:59 UTC
Labels: bug
