### ISSUE TITLE
Force Close!

### ISSUE THREAD

**Issue by yushril** [LucasGGamerM/moshidon#19] opened 2023-01-02 14:07 UTC
The app suddenly forces a close when I click on another account on the profile I'm visiting. 

Moshidon Version:
v1.1.4+fork.82.moshinda (82)

https://user-images.githubusercontent.com/10511546/210241884-8362bbf4-9a9b-45d7-a79d-153a0c4459e2.mp4

**Comment by LucasGGamerM** [comment] 2023-01-02 14:47
The bug was caused by something related to the bot icon. It's fixed on commit ac3875fe08f5ea0d7b65c464f1edd0f7d66657d5

**Closed by LucasGGamerM** 2023-01-02 14:47 UTC
Labels: bug
