### ISSUE TITLE
Clicking translate affects the images 

### ISSUE THREAD

**Issue by maikelthedev** [LucasGGamerM/moshidon#471] opened 2024-07-20 06:04 UTC
**Describe the bug**

Here's a video https://vmst.io/@maikel/112817288493927484

You scroll in a timeline and click translate and sometimes the images change to previous images on another toots. 

**To reproduce**

Scroll, scroll, press translate. 

**Does this happen in the official app?**

I always use latest nightly

**Comment by FineFindus** [comment] 2024-07-20 09:50
Duplicate of https://github.com/LucasGGamerM/moshidon/issues/335.

**Closed** 2024-07-20 13:36 UTC
Labels: bug
