### ISSUE TITLE
[Request] Changing font/interface size

### ISSUE THREAD

**Issue by notBradPitt** [LucasGGamerM/moshidon#226] opened 2023-07-07 15:47 UTC
Love this app, the design feels like a massive improvement and leaps ahead of other clients I've tried. However, elements such as the interaction count (displayed next to the buttons) are unreadable on smaller device or devices with larger font. It either shows "..." or "1...".

An option to manually set font size would be a very useful addition 👍

**Comment by FineFindus** [comment] 2023-07-07 20:24
Somewhat duplicate issue: https://github.com/LucasGGamerM/moshidon/issues/182

**Comment by LucasGGamerM** [comment] 2023-07-07 20:32
Closed as duplicate of #182

**Closed by LucasGGamerM** 2023-07-07 20:32 UTC
