### ISSUE TITLE
Emoji React Crash

### ISSUE THREAD

**Issue by diziara** [LucasGGamerM/moshidon#375] opened 2024-04-10 23:51 UTC
**Describe the bug**

When using the emoji react picker, if one selects an emoji via the keyboard's suggestion feature, it causes Moshidon to crash. If selecting emoji from the emoji picker of the keyboard app, the app does not crash.

**To reproduce**

1. View a timeline or toot.
2. Click on the + button to add an emoji react.
3. Tap the search bar that pops up.
4. Type something to search for the emoji you want.
5. Select emoji from the text prediction suggestions.
6. App crashes

This has been verified on two different Sharkey instances, using both Gboard and Swiftkey keyboards. (Attempted to also test with the Samsung keyboard, but that piece of dren wouldn't give me emoji suggestions despite the setting being turned on.)

**Does this happen in the official app?**
I don't know, this is with a Sharkey account, which the official app does not support. (Mastodon is not the only Fedi front end out there, and the Misskey forks don't have any good apps. Yours mostly works other than a few quirks.)

**Version**

Moshidon version: v2.1.4+fork.104.moshinda-play

**Crash log**

2.1.4+fork.104.moshinda-play (104)
2024-04-10T23:40:46.279Z

java.lang.StringIndexOutOfBoundsException: length=1; index=4
 at java.lang.String.substring(String.java:2479)
 at org.joinmastodon.android.ui.CustomEmojiPopupKeyboard$5.onTextChanged(CustomEmojiPopupKeyboard.java:171)
 at android.widget.TextView.sendOnTextChanged(TextView.java:13007)
 at android.widget.TextView.handleTextChanged(TextView.java:13136)
 at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:16779)
 at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1268)
 at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
 at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
 at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:38)
 at android.view.inputmethod.BaseInputConnection.replaceTextInternal(BaseInputConnection.java:1031)
 at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:962)
 at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:241)
 at com.android.internal.inputmethod.EditableInputConnection.commitText(EditableInputConnection.java:222)
 at android.view.inputmethod.RemoteInputConnectionImpl.lambda$commitText$16(RemoteInputConnectionImpl.java:637)
 at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$DuD803urSTti1OmMx2Hq0yX1sSU(Unknown Source:0)
 at android.view.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda15.run(Unknown Source:8)
 at android.os.Handler.handleCallback(Handler.java:958)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:230)
 at android.os.Looper.loop(Looper.java:319)
 at android.app.ActivityThread.main(ActivityThread.java:8893)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by DeadSuperHero** [comment] 2024-04-11 00:11
Akkoma user here, similar situation when trying to enter standard emoji from keyboard search. I'm using GBoard, YMMV.

Steps to reproduce:
1. Go to post
2. Tap + Button
3. Type the name close to the one you want
4. Tap the emoji that appears when the keyboard includes it in word recommendations. 

A workaround, which does *not* crash:
1. Go to post
2. Tap + Button
3. Tap the smiley key next to the spacebar
4. Pick the emoji, tap it directly.

**Comment by ExperiencersInternational** [comment] 2024-04-12 17:12
Can't reproduce on the app from F-Droid on wetdry.world or lethallava.land.

**Comment by LucasGGamerM** [comment] 2024-04-12 17:48
Strangely enough I didn't manage to reproduce this one on either the stable release nor the nightly. Which is weird. I think I know what is causing it, but I am not yet sure about it

**Comment by LucasGGamerM** [comment] 2024-04-12 19:30
Fixed with ff95876

**Closed by LucasGGamerM** 2024-04-12 19:30 UTC
Labels: bug
