### ISSUE TITLE
"This list is empty" on the posts section of explore tab. 

### ISSUE THREAD

**Issue by ChildishGiant** [LucasGGamerM/moshidon#211] opened 2023-06-08 11:18 UTC
![Screenshot_20230608-121651~2.png](https://github.com/LucasGGamerM/moshidon/assets/13716824/e7be4a69-3a5e-47da-815c-83c6a912ccef) I'm aware this could be something to do with instance I use or something like that but I'm too daft to know what 😅

**Comment by FineFindus** [comment] 2023-06-11 19:47
Please provide more information. With the information currently available, all I can say is that it works on my device. An indication of a problem would be if the trending posts were also not available in the web client.

**Comment by LucasGGamerM** [comment] 2023-06-11 19:56
> ![Screenshot_20230608-121651~2.png](https://user-images.githubusercontent.com/13716824/244366243-e7be4a69-3a5e-47da-815c-83c6a912ccef.png) I'm aware this could be something to do with instance I use or something like that but I'm too daft to know what sweat_smile

Are you on akkoma by any chance? If so, then such info doesn't exist.

**Comment by LucasGGamerM** [comment] 2023-09-17 22:39
Closed as expected behavior and not a bug

**Closed by LucasGGamerM** 2023-09-17 22:39 UTC
