### ISSUE TITLE
Pleroma 

### ISSUE THREAD

**Issue by s0mt0chukwu** [LucasGGamerM/moshidon#322] opened 2023-12-24 15:21 UTC
Ability to access any pleroma instance from Moshidon

**Comment by LucasGGamerM** [comment] 2023-12-24 15:50
You can already do so. What problem have you been experiencing?

**Comment by s0mt0chukwu** [comment] 2023-12-25 00:16
I can access instances like poa.st but I can't access clubcyberia.co

**Comment by LucasGGamerM** [comment] 2023-12-26 19:33
It seems like a hostname issue, which is weird, because it works on the browser last time I tried it

**Comment by LucasGGamerM** [comment] 2023-12-26 19:38
> It seems like a hostname issue, which is weird, because it works on the browser last time I tried it

Nah, I mistyped the instance name, and this looks like a duplicate of #307

**Closed by LucasGGamerM** 2023-12-26 19:38 UTC
