### ISSUE TITLE
bug(notification) not possible to expand notifications 

### ISSUE THREAD

**Issue by FineFindus** [LucasGGamerM/moshidon#56] opened 2023-01-24 22:14 UTC
**Describe the bug**
Since the latest version, it is no longer possible to expand notifications, to reveal the full text. Instead their all truncated early. 

**To Reproduce**
1. Get a notification referencing a longer text post 
2. Open the notification shade
3. See truncated text, notice the missing expand icon

**Screenshots and screen recordings**
![Example](https://user-images.githubusercontent.com/63370021/214432872-d6500533-9e82-4374-8c95-672d61e12206.jpg)

**Version**
Moshidon version: v1.1.4+fork.87.moshinda

**Additional context**
Possibly relevant [docs page.](https://developer.android.com/develop/ui/views/notifications/expanded#java)

**Comment by LucasGGamerM** [comment] 2023-01-25 00:44
I actually can't reproduce this on my device. Would you please provide phone model + system version? I have a pixel 3 running Android 13, and I cannot reproduce this specific bug.

**Comment by FineFindus** [comment] 2023-01-25 08:27
This is a Huawei device running Android 10. It is quite possible, that this bug is related to the Android version, as a lot has changed with notifications between versions.

**Comment by LucasGGamerM** [comment] 2023-01-29 13:42
I believe this should be fixed now, as with release 88 the notification style changed from inbox back to the known working one.

**Closed by LucasGGamerM** 2023-01-29 13:42 UTC
Labels: bug, can't reproduce

**Comment by FineFindus** [comment] 2023-01-29 13:44
I will keep an eye out for it, and re-open it otherwise. Thanks!
